#!/bin/bash

# bash generate random alphanumeric string

# default values
LENGTH=20
ITERATION=1


help(){
  echo "genpassword [-l LENGTH] [-n PASSWORDS]"
  exit
}


while getopts 'l:n:h' OPTION; do
  case "$OPTION" in
    l)
      LENGTH=$OPTARG
      if [ $LENGTH -le 0 ]; then
        echo "First argument (password length) must be at least 1"
        exit
      fi

      ;;

    n)
      ITERATION=$OPTARG
      if [ $ITERATION -le 0 ]; then
        echo "Second argument (n. of generated passwords) must be at least 1"
        exit
      fi
      ;;

    h)
      help
      ;;

  esac
done

echo "$LENGTH chars password will be generated"

for (( i = 0 ; i < $ITERATION ; i++ )); do
  cat /dev/urandom | tr -dc 'a-zA-Z0-9!#$%&*,.=?@^' | fold -w $LENGTH | head -n 1
done
