#!/bin/bash

# bash generate random 32 character alphanumeric string

# check if $1 argument exists, if not default length password will be generated
if [ -z "$1" ]; then
  # default password length is 20
  LENGTH=20
else
  # if $1 argument exists check if is greater than 0
  if [ $1 -le 0 ]; then
    echo "First argument must be at least 1"
    exit
  else
    LENGTH=$1
  fi
fi

cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $LENGTH | head -n 1
